# Generated by Django 5.2.1 on 2025-06-02 10:06

import link_shortener.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_code', models.CharField(default=link_shortener.utils.generate_short_code, max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_visited_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
